### ISSUE TITLE
Admin: Refine CDP Roadmap Project Board

### ISSUE THREAD

**Issue by hawkticehurst** [CouncilDataProject/cdp-roadmap#1]
As we're setting up this repo I'd love some help/discussion regarding how we structure the Project Board of this repo to best suit our needs.

The repo is loosely modeled off of the [GitHub public roadmap](https://github.com/github/roadmap/projects) and can be referenced as we figure out what we want to do.

In particular, how we organize the project board would be a nice first topic. GitHub organizes its roadmap by quarter, but since we operate more loosely I've temporarily included "To Do", "In Progress", and "Done" columns.

**Comment by JacksonMaxfield** [comment]
I think having ours just be simpler buckets makes sense. I would like to make a request / comment, can we have the columns as:

"Ideas", "To Do", "In Progress", "Done"?

I think there is value in having a bucket that is in the "planning" phase basically.

**Comment by hawkticehurst** [comment]
Oh yeah, great idea. Consider it done.

**Comment by JacksonMaxfield** [comment]
I changed `Ideas` to `Planning` as we now have an `idea` label I didn't want to get add confusion as to the stages of the process.

So far after transferring issues over to here I am already happy to see this general progress and planning.

It would be interesting if we had labels or some system added that @sarahjliu mentioned for RICE? Like for issues that move from `Planning` to `To Do` they specifically have to be checked / RICE information be added?

**Comment by JacksonMaxfield** [comment]
Do things like #13 belong here. I personally belive so but how should we tag them and such?
