### ISSUE TITLE
Facilitate Access to CDP Data

### ISSUE THREAD

**Issue by nniiicc** [CouncilDataProject/cdp-roadmap#19]
## Idea / Feature
Support programmatic use of CDP data 

## Use Case / User Story

- I am a political scientist. I want to query a CDP API so that I can obtain all transcripts from city councils in the USA where the phrase "critical race theory" appears. 
- I am a political scientist. I want to query a CDP interface so that I can obtain all transcripts from city councils in the USA where the phrase "critical race theory" appears. I want the interface to allow me to select criteria like a a date range, enter a keywords, choose the format of delivery etc. 

## Solution

- A documented restfulAPI with examples how to query within and across CDP instances 
- A GUI that allows a user to assemble and download a dataset

## Alternatives

- Pre-packaging  / releasing CDP data at regular intervals. We could just say here is a giant tarball of all transcripts as a first step, but ultimately this is a poor solution to encouraging more programmatic use of CDP data. 

## Stakeholders

My use cases are for research - but it could be useful to lots of people from lots of different backgrounds (computational journalism, advocacy group, etc) that want to use CDP data 

## Other Notes

Left above blank because ⏳

**Comment by JacksonMaxfield** [comment]
Going to move some of the ideas in this issue over to #3

Some nice additions here
