### ISSUE TITLE
Link to public roadmap broken

### ISSUE THREAD

**Issue by brivolbm7q** [CouncilDataProject/cdp-roadmap#30]
On the roadmap page (https://github.com/CouncilDataProject/cdp-roadmap?tab=readme-ov-file), the link to the public roadmap is broken (results in 404 error).

**Comment by evamaxfield** [comment]
Hey! Sorry the roadmap is really just the issues board: https://github.com/CouncilDataProject/cdp-roadmap/issues

At one point it was nicer and I had written up a document somewhere that I now don't know if I can find.

Secondly and separately, CDP isn't being actively developed anymore. Although we have had some interest from a few people to take over a few of the instances and keep them running.
